<template>
 <div>
 	<div class="variableSearchBox">
	<!--   <el-select v-model="value" placeholder="请选择">
	    <el-option
	      v-for="item in 6"
	      :key="item.value"
	      :label="item.label"
	      :value="item.value">
	    </el-option>
	  </el-select>
	  <el-input v-model="input" placeholder="请输入内容"></el-input>
	  <el-select v-model="value" placeholder="请选择">
	    <el-option
	      v-for="item in options"
	      :key="item.value"
	      :label="item.label"
	      :value="item.value">
	    </el-option>
	  </el-select>
	  <el-input v-model="input" placeholder="请输入内容"></el-input>
 -->
 	</div>
  <el-table
      :data="variablePointData"
      style="width: 100%">
      <el-table-column
        prop="serial_num"
        label="serial_num"
        width="90"
        >
      </el-table-column>

      <el-table-column
        prop="point_name"
        label="point_name"
        width="180"
        >
      </el-table-column>
       <el-table-column
        prop="current_value"
        label="current_value"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="force_value"
        label="force_value"
        width="130"
        >
        <template>
        	<!-- <el-input v-model="input" placeholder="请输入内容"></el-input> -->
        </template>
      </el-table-column>
      <el-table-column
        prop="id_code"
        label="id_code"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="extens_code"
        label="extens_code"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="designation"
        label="designation"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="mod_var"
        label="mod_var"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="sim_var"
        label="sim_var"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="swi_var"
        label="swi_var"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="signal_from"
        label="signal_from"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="signal_to"
        label="signal_to"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="io_type"
        label="io_type"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="functional_class"
        label="functional_class"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="signal_spec"
        label="signal_spec"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="power_supply"
        label="power_supply"
        width="130"
        >
      </el-table-column>
      
      <el-table-column
        prop="meas_unit"
        label="meas_unit"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="meas_min"
        label="meas_min"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="meas_max"
        label="meas_max"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="elec_unit"
        label="elec_unit"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="elec_min"
        label="elec_min"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="elec_max"
        label="elec_max"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="level"
        label="level"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="diagram_number"
        label="diagram_number"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="rev_note2"
        label="rev_note2"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="remarks"
        label="remarks"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="io"
        label="io"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="comment"
        label="comment"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="cabinet_num"
        label="cabinet_num"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="cabinet_type"
        label="cabinet_type"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="slot_num"
        label="slot_num"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="card_type"
        label="card_type"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="channel_num"
        label="channel_num"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="terminal_type"
        label="terminal_type"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="terminal_channel"
        label="terminal_channel"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="instrument_identification"
        label="instrument_identification"
        width="180"
        >
      </el-table-column>
      <el-table-column
        prop="setpoint_type"
        label="setpoint_type"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="setpoint_value"
        label="setpoint_value"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="setpoint_energ"
        label="setpoint_energ"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="action"
        label="action"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="test_cabinet_num"
        label="test_cabinet_num"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="test_cabinet_type"
        label="test_cabinet_type"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="test_slot_num"
        label="test_slot_num"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="test_card_type"
        label="test_card_type"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="test_channel_num"
        label="test_channel_num"
        width="130"
        >
      </el-table-column>
      <el-table-column
        prop="force_flag"
        label="force_flag"
        width="130"
        >
      </el-table-column>
      

    </el-table>
 </div>
</template>
<script>
 export default{
 	name:'variableTable',
 	data(){
 		return {}
 	},
 	props:['variablePointData'],
 	created(){
 		// console.log(this.variablePointData);
 	}
 }
</script>